### ISSUE TITLE
Deploy a Demo to Netlify?

### ISSUE THREAD

**Issue by cadbox1** [maiermic/reveal-md-mermaid-animation-example#2]
hey @maiermic, nice job on the library!

have you thought about deploying it to somewhere like [Netlify](https://www.netlify.com/) so people can check out a demo without pulling the code down?

happy to help if you're not sure how but Netlify makes it pretty easy.

**Comment by maiermic** [comment]
I've deployed the presentation to Github Pages and added the link to the Readme: https://maiermic.github.io/reveal-md-mermaid-animation-example/

**Comment by cadbox1** [comment]
that looks great! well done!

you might want to add it to the repo details so other people can find it: https://stackoverflow.com/a/62767178/728602

it looks fantastic!

**Comment by maiermic** [comment]
Thanks, I've added it as website :+1:
